### ISSUE TITLE
Apps needs established network connection

### ISSUE THREAD

**Issue by LorenzMeier** [ologic/Tango#10]
Right now the app requires Wifi (and maybe a valid IP address). I'm not always having this available even in the early testing now @bblodget any chance of quickly changing this?

**Comment by bblodget** [comment]
I think the only way to do this is to remove rosjava from the app.  This is doable but requires changing the structure of the app.  Maybe it would be better for me to create a new app say "tango_mavlink" which would publish the mavlink messages but not the ros messages.  Suggestions welcome.

**Comment by bblodget** [comment]
I think I fixed the problem without removing rosjava.  If you don't have a wifi connection, select "New Private Master" under "Show advanced options".  This option was not working correctly and I believe my latest commit fixes the issue.

**Comment by mbrandonhurd** [comment]
Works like a charm!

**Comment by LorenzMeier** [comment]
Thanks, great!
