### ISSUE TITLE
Update to more recent AndroidStudio version

### ISSUE THREAD

**Issue by simonlynen** [ologic/Tango#2]
Because of an incompatibility between studio 0.6.1 and 0.9 it is not possible to use the projects from this repo with a recent android studio version. I am happy helping with this.

**Comment by rohbotics** [comment]
I have created branch patch-2 and added this change 94ce3a66450baabc28e2e2d4d8b2c40eb3d2778f

**Comment by rohbotics** [comment]
Could someone please test this change in android studio 0.8.x ?

**Comment by mbrandonhurd** [comment]
Rohan,

I tested the change in studio 0.8.2 and here is what I get.

A problem occurred configuring root project 'rostango'.

> Could not resolve all dependencies for configuration ':classpath'.
> Could not resolve org.ros.rosjava_bootstrap:gradle_plugins:0.1.22.
>      Required by:
>          :rostango:unspecified
>       > java.lang.NullPointerException (no error message)

Any thoughts? Thanks!

**Comment by rohbotics** [comment]
Weird, try changing line 36 in rostango/build.gradle to:
`classpath group: 'org.ros.rosjava_bootstrap', name: 'gradle_plugins', version: '[0.1,0.2)'`

**Comment by mbrandonhurd** [comment]
Still get an error, here it is.

> Could not find any version that matches org.ros.rosjava_bootstrap:gradle_plugins:[0.1,0.2).
>      Required by:
>          :rostango:unspecified

**Comment by rohbotics** [comment]
Did you run catkin_make

```
cd <Root Of Repository>/ROSTango
catkin_make
```

**Comment by rohbotics** [comment]
Are you in the patch-2 branch, i haven't  pushed the changes to the master branch yet, 0.8.x will only work on the patch-2 branch.
